### ISSUE TITLE
Commands are not saved

### ISSUE THREAD

**Issue by TheoForay** [mikebattista/PowerShell-WSL-Interop#23]
I followed the instructions on the README, installed PS Core, the package with the package manager, I can add new aliases (with Import-WslCommand) of my WSL, and it works. But when I close the PowerShell window, and open a new one, the aliases are gone.

**Comment by mikebattista** [comment]
Are you adding the Import-WslCommand call to your PowerShell profile?

**Comment by TheoForay** [comment]
My bad, I definitely read the explanations too quickly 😅
Thank you for the fast answer, it fixed it indeed!
Love your project
