### ISSUE TITLE
Error loading profile

### ISSUE THREAD

**Issue by 573** [mikebattista/PowerShell-WSL-Interop#24]
When installing the module using

    Install-Module WslInterop

adding

    Import-WslCommand "awk", "emacs", "grep", "head", "less", "ls", "man", "sed", "seq", "ssh", "tail", "vim", "bash"
    $WslDefaultParameterValues["grep"] = "-E"
    $WslDefaultParameterValues["less"] = "-i"
    $WslDefaultParameterValues["ls"] = "-AFh --group-directories-first"
    $WslDefaultParameterValues["bash"] = "--login --init-file ~/.nix-profile/etc/profile.d/nix.sh"

and the reloading profile I get a bunch of:

>Cannot index into a null array.
At ...\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:8 char:1
>+ $WslDefaultParameterValues["grep"] = "-E"
>+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>+ FullyQualifiedErrorId : NullArray

**Comment by 573** [comment]
My bad, just saw [that](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-6#creating-hash-tables)), you also mentioned it.

**Comment by 573** [comment]
Thx @mikebattista for the great module it is outstanding in easing my work, can i. e. use `bash -c 'nix-shell --pure -p pandoc -p texlive.combined.scheme-small'` instead of tedious custom functions in Profile.ps1 or even make an alias for that now.

**Comment by mikebattista** [comment]
Glad you find this project helpful.

For the nix-shell command question, could you clarify what it is you want to be able to do? What is it that you want to type into PowerShell and what do you want that to do?

**Comment by 573** [comment]
I. e. when I wanted a shell with pandoc and pdflatex available I typed that command (I even could wrap it further into a pwsh function to just have to type `pandoc -o cheatsheet.pdf cheatsheet.tex` directly without the extra prompt but to show that function definition would surely bloat the scope of a demo) to get a prompt where I typed:

    pandoc -o cheatsheet.pdf cheatsheet.tex

Thus I can convert a tex file from the internet to a pdf using tex and everything just under the hood, basically staying in my powershell session.

Does that sound weird or complicated ?

**Comment by mikebattista** [comment]
Sounds like if you have the pandoc package installed within WSL, you should be able to add `Import-WslCommand "pandoc"` to your PowerShell profile to replace your custom function. Then you should be able to call it as shown in all the [demos](https://pandoc.org/demos.html) without needing to leave your PowerShell session.

Would that work for you?

**Comment by 573** [comment]
Thanks, it's fine. Just works.
