### ISSUE TITLE
Wsl Default Paramter Error

### ISSUE THREAD

**Issue by Heinzler** [mikebattista/PowerShell-WSL-Interop#25]
Hi,

I get an error when using $WslDefaultParameterValues on Powershell 7.0.0 and WslInterop 0.2.2

`$WslDefaultParameterValues["ls"] = "-AFh --group-directories-first"
InvalidOperation: Cannot index into a null array.`

The commands themselves work, but also the resolving of Linux paths does not work. I tested on Windows 10 1809 and 1909.

Best regards

**Comment by mikebattista** [comment]
Did you create the hash table first?

`$WslDefaultParameterValues = @{}`.

Which commands are you attempting to resolve Linux paths with?

**Comment by Heinzler** [comment]
Thank you very much, now the default parameters work. I have used this guide and unfortunately overlooked on github to create the hashtable first.
https://devblogs.microsoft.com/commandline/integrate-linux-commands-into-windows-with-powershell-and-the-windows-subsystem-for-linux/ 

For example, when I try to use 
ls /et
to complete the path /etc, it doesn't work.

What am I doing wrong?

**Comment by mikebattista** [comment]
Awesome.

Can you run `Import-WslCommand "ls"` first? Then try `ls /et<TAB>` to autocomplete?

It's possible either `Import-WslCommand "ls"` was not run, so `ls` is actually still the default alias for Get-ChildItem, or maybe you ran it, but didn't add it to your PowerShell profile, and now you're in a new PowerShell session so `ls` again would still be the default alias for Get-ChildItem.

If this doesn't help, please send me the output of `gcm ls` and I'll look into it further.

I'm on 1909, PS 7, and WslInterop 0.2.2 and Linux path completion works for me.

**Comment by Heinzler** [comment]
I put that in my profile.
`Import-WslCommand` "awk", "emacs", "grep", "head", "less", "ls", "man", "sed", "seq", "ssh", "tail", "touch"`

Here is the output
`PS C:\> gcm ls

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        ls                                                 0.2.2      WslInterop

PS C:\>`

thanks for your help

**Comment by mikebattista** [comment]
Could you provide the output of `$WslCompletionFunctions`?

**Comment by Heinzler** [comment]
The Output is nothing

**Comment by mikebattista** [comment]
That's a problem. We need to figure out why that isn't populated.

As a test, could you try `$WslCompletionFunctions = @{ ls = '_longopt' }` and then try `ls /et<TAB>` again?

**Comment by Heinzler** [comment]
unfortunately does not work

**Comment by mikebattista** [comment]
Is WSL installed and working? Can you autocomplete within WSL?

When you run ls and manually type a Linux path, does it return results from WSL?

**Comment by Heinzler** [comment]
Is WSL installed and working? yes it is a debian

Can you autocomplete within WSL? yes

When you run ls and manually type a Linux path, does it return results from WSL? yes

**Comment by mikebattista** [comment]
Ok. I was able to repro what you're seeing with Debian. I am using Ubuntu.

I think the problem is the Debian distro doesn't include `/usr/share/bash-completion/bash_completion` like Ubuntu does. If I copy this file over from the Ubuntu distro, everything works as expected.

Could you try that?

I don't know why the Debian distro doesn't include this file, but it is required for the bash completion interop to work.

**Comment by Heinzler** [comment]
can I download the file somewhere or do I need to install Ubuntu? Is it important which version of Ubuntu the file comes from?

**Comment by mikebattista** [comment]
Actually it looks like what you need is the `bash-completion` package which includes this file.

`sudo apt install bash-completion`

Could you try that and let me know if it works?

If so, I will add this as a prerequisite in the README.

**Comment by Heinzler** [comment]
yes it works, thank you very much!

**Comment by mikebattista** [comment]
Awesome. Thanks for pointing this out.
