### ISSUE TITLE
\\wsl$\<distro_name>\<path> UNC path syntax is not converted

### ISSUE THREAD

**Issue by archilkarchava** [mikebattista/PowerShell-WSL-Interop#28]
**Describe the bug**
\\wsl$\<distro_name>\<path> UNC path syntax is not converted to linux path
e.g. \\wsl$\Ubuntu\etc\wsl.conf to /etc/wsl.conf
**To Reproduce**
1. Start `pwsh`
2. Enter imported command like `vim '\\wsl$\Ubuntu\etc\wsl.conf'`
3. Command is not converted to /etc/wsl.conf

**Expected behavior**
Path conversion working.
e.g. convert \\wsl$\Ubuntu\etc\wsl.conf to /etc/wsl.conf

**Desktop (please complete the following information):**
* Windows 2004 (OS Build (19041.208)
* Ubuntu 20.04 on Windows 10 x86_64 on 4.19.84-microsoft-standard
* GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)

**Additional context**
Good thing to note is that this still won't work across multiple wsl distros.
`vim '\\wsl$\Ubuntu\etc\wsl.conf'`
`vim '\\wsl$\Debian\etc\wsl.conf'`

**Comment by mikebattista** [comment]
Can you share more details on why you're passing the UNC share vs. just `/etc/wsl.conf`?

Are you trying to differentiate between WSL distros?

**Comment by archilkarchava** [comment]
@mikebattista It's not really a problem, just found it inconsistent with other commands, that's all.

**Comment by mikebattista** [comment]
Ok. I wouldn't expect this to work. 

The design is Windows paths (e.g. C:\Windows) will be translated to the appropriate mount point within WSL (e.g. /mnt/c/Windows) and Linux paths should just be passed as is (e.g. /etc/wsl.conf). I don't think trying to translate an already translated virtual path like the UNC paths is something I want to incorporate here. Those UNC paths are for Windows commands not for Linux commands.

If you were trying to differentiate distros by doing this, my recommendation would be to set the default WSL distro via `wsl -s` before calling the imported command.
