### ISSUE TITLE
Cannot run npm/nvm

### ISSUE THREAD

**Issue by adambajguz** [mikebattista/PowerShell-WSL-Interop#30]
**Describe the bug**
Cannot run `npm`.

**To Reproduce**
In Ubuntu-20.04 run:
`wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash`
`source ~/.bashrc`
`nvm install --lts`
`nvm use --lts`
`npm --version` - should return version

Run PowerShell Script:
```
    Import-Module "WslInterop"
    Import-WslCommand "nvm", "npm", "ls"
    nvm --version
    npm --version
    ls -la
```

**Expected behavior**
I've thought this PowerShell module solves https://stackoverflow.com/questions/61823716/wsl-on-windows-10-not-loading-config-files-when-ran-interoperabiltiy

**Comment by mikebattista** [comment]
I just ran `apt install npm` inside my Ubuntu WSL 2 image, then ran `Import-WslCommand "npm"` in a PowerShell session in Windows and was able to run `npm --version` just fine from PowerShell in Windows.

Could you provide more details on your repro? Did none of the commands you imported work?

**Comment by adambajguz** [comment]
Sorry, I forgotten to mention that both `nvm` and `nmp` doesn't work.

![image](https://user-images.githubusercontent.com/23001378/116977071-453a1780-acc2-11eb-898e-a3369b3583cb.png)

The script I run:
```
Import-WslCommand "nvm", "npm", "ls"

nvm --version
npm install
npm run buildcss
ls -la
```

**Comment by mikebattista** [comment]
Do you have multiple WSL distributions installed? Is Ubuntu on the right your default WSL distribution?

**Comment by adambajguz** [comment]
```
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
docker-desktop-data
docker-desktop
```

Yes, Ubuntu is a default distribution

**Comment by mikebattista** [comment]
What does `wsl npm --version` return?

**Comment by adambajguz** [comment]
It returns `/bin/bash: npm: command not found`, and this is the main reason I thought PowerShell-WSL-Interop module will solve this. Before I found your module, I've found this information https://stackoverflow.com/questions/61823716/wsl-on-windows-10-not-loading-config-files-when-ran-interoperabiltiy

**Comment by adambajguz** [comment]
Currently, it looks like: either I cannot use `nvm` or sth from `.profile` etc. is not loaded with WslInterop.

**Comment by mikebattista** [comment]
Where are nvm and npm installed? The errors you're getting suggest WSL can't find the binary in the standard PATH locations.

The WslInterop module just passes through to WSL, so if `wsl npm --version` doesn't work, `npm --version` won't work either unless something about your environment is addressed.

Is your .profile or .bashrc doing something that helps resolve the nvm and npm commands from somewhere outside of the standard PATH locations?

**Comment by adambajguz** [comment]
_Where are nvm and npm installed?_ - yes, they are. See the screenshot above.

_Is your .profile or .bashrc doing something that helps resolve the nvm and npm commands from somewhere outside of the standard PATH locations?_ - I don't really know, but npm and nvm somehow work when executed from Ubuntu directly, so there must be some difference between WSL iterop and direct call from Ubuntu.

**Comment by mikebattista** [comment]
I asked where are they installed, not if. What does `which npm` return in Ubuntu?

There's nothing specific to WslInterop here. WSL is launching a non-interactive session which doesn't load profiles.

https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files may provide some clues how to get this working. Specifically the "Invoked non-interactively" section. You could try setting `$WslEnvironmentVariables["BASH_ENV"] = "~/.bashrc"` or one of your other relevant profiles and see if that helps when you call `npm --version` from PowerShell.

**Comment by adambajguz** [comment]
Oh, sorry I misread the question.


![image](https://user-images.githubusercontent.com/23001378/116986075-a5828680-accd-11eb-8277-f8f2ccfc792c.png)

How should I set WslEnvironmentVariables in `.ps1` file?

```
    Import-WslCommand "nvm", "npm", "ls"
    $WslEnvironmentVariables["BASH_ENV"] = "~/.bashrc"
```

throws the following error:

![image](https://user-images.githubusercontent.com/23001378/116986698-6274e300-acce-11eb-8a22-3763bf631479.png)

**Comment by mikebattista** [comment]
Ok. It's no wonder bash through WSL can't find these given where they're installed. One of your profiles is likely adding this location to the PATH.

You need to initialize the hash table first. Add `$WslEnvironmentVariables = @{}` before setting BASH_ENV.

**Comment by adambajguz** [comment]
Thanks, I will experiment with this and reply later

**Comment by mikebattista** [comment]
From some quick tests, I don't think `$WslEnvironmentVariables` will work, since it's set too late in the process it seems.

Another approach you could try is:

* `[System.Environment]::SetEnvironmentVariable("BASH_ENV", "~/.bashrc")`
* `[System.Environment]::SetEnvironmentVariable("WSLENV", "$($Env:WSLENV):BASH_ENV/u")`

With these environment variables set, I do see `~/.bashrc` executing before the command I pass to WSL. That seems promising.

**Comment by adambajguz** [comment]
I've spent some time trying to call nvm/npm from WSL interop without success. The limitation is WSL not your library; thus, I will this issue.

**Comment by kladd** [comment]
This is inelegant, but I accomplished this by piggybacking the WSL `--shell-type` argument with the distro flag:
```powershell
$WslDefaultParameterValues = @{}
$WslDefaultParameterValues["-d"] = "Ubuntu --shell-type login"
```
