### ISSUE TITLE
Make WslDefaultParameterValues dynamic not static

### ISSUE THREAD

**Issue by Ergamon** [mikebattista/PowerShell-WSL-Interop#32]
**Is your feature request related to a problem? Please describe.**
Currently we can set the default parameter values in a hashtable named WslDefaultParameterValues.

This is basically a Dictionary<string, string>.

**Describe the solution you'd like**
I would like to see a modification, e.g. $WslDefaultParameters.

This should check the type. If it is a string, then work like before.

If it is a scriptblock, then get the value at runtime by executiong the function.

**Additional context**
In case you are asking why I want this:

I am using a commandline tool accepting passwords and want to use PowerShell´s secret store for that.

To combine these, I can to the following:

ansible-playbook playbook.yaml -i /hosts --extra-vars "ansible_become_pass=$((Get-Secret MySecret).Password | ConvertFrom-SecureString -AsPlainText)"

Of course the last parameter is almost always needed and very clumsy to write in this notation.

So what I want to do, is store this expression as a default parameter.

But this does not work as when I put it this way in the dictionary, the $(xxx) part is not evaluated.

I can do the following:
$WslDefaultParameterValues = @{ "ansible-playbook" = "--extra-vars ansible_become_pass=$((Get-Secret MySecret).Password | ConvertFrom-SecureString -AsPlainText)" }

This works of course, but now

$WslDefaultParameterValues[ "ansible-playbook"]

shows my password.

To make the usage conveniant, I would suggest accepting strings and functions. So the typical case works like before, but there is an additional option to make the default parameter generation dynamic.

**Comment by mikebattista** [comment]
Could you try this?

* Open `(gmo WslInterop).Path` to edit
* Add ``if (`$defaultArgs -is [scriptblock]) { `$defaultargs = . `$defaultargs }`` between [these lines](https://github.com/mikebattista/PowerShell-WSL-Interop/blob/d37a4f03808522f6d78eb02a27abc6ebbcdc9545/WslInterop.psm1#L93-L94)
* Restart PowerShell to reload the module
* Set `$WslDefaultParameterValues["ansible-playbook"] = { "--extra-vars ansible_become_pass=$((Get-Secret MySecret).Password | ConvertFrom-SecureString -AsPlainText)" }`
* Run `ansible-playbook`

Let me know if that works for you.

**Comment by Ergamon** [comment]
Hello Mike,
this works like a charm.

I am no exception to the typical user who only addresses the developers, if they face a problem. So I want at least to take this post here to thank you for your great module. Probably not too many are aware of this little gem, but this module makes working with PowerShell and WSL so much better.

**Comment by mikebattista** [comment]
Thanks for testing it and the kind words. I'm glad you like the module.

I'll add this feature to the module and publish an update. Reopening to track that.
