### ISSUE TITLE
wsl.exe ls is super slow (is this due to vmIdleTimeout=60 seconds)

### ISSUE THREAD

**Issue by SagaraBattousai** [mikebattista/PowerShell-WSL-Interop#38]
Hi, Not sure if this is the correct place to ask this, my apologies if not. I followed the awesome blog that links to this repo and It has worked for a long time. However on windows 11 I'm noticing that the first time you call ls (for example) it's very slow (3 to 5 seconds to list a couple of files). It seems to speed up after that but then will occasionally become slow again.

I was wondering if it were due to the new vmIdleTimeout setting for wsl2 on windows 11; however I cannot seem to get consistent result to confirm that this is the case (even when setting it to 3600000 (A.K.A 1 hour).

Has anyone else experienced the same issue?

**Comment by mikebattista** [comment]
I would file an issue at https://github.com/microsoft/WSL/issues if you're seeing this with wsl.exe.
