### ISSUE TITLE
-exec Parameter for "find" does not work properly

### ISSUE THREAD

**Issue by aurora** [mikebattista/PowerShell-WSL-Interop#41]
Not sure if this issue can be solved, anyway - thanks a ton for your great work on this 😄 

**Describe the bug**

There are various bugs with the "-exec" parameter of the find command. Arguments to `-exec` do not work and result in errors.

**To Reproduce**

```
find . -exec echo blub \;
find . -exec echo {} \;
```

**Expected behavior**

The first command should output "blub" for every item found.
The second command should output the pathname of every item found.

**Screenshots**

Output of first command:

```
find: missing argument to `-exec'
```

Output of second command:

```
Test-Path:
Line |
  22 |              } elseif (Test-Path $args[$i] -ErrorAction Ignore) {
     |                                  ~~~~~~~~~
     | Cannot evaluate parameter 'Path' because its argument is specified as a script block and there is no input. A script block cannot be evaluated without input.
find: missing argument to `-exec'
```

**Desktop (please complete the following information):**
 - Windows 11, WSL2

**Comment by mikebattista** [comment]
`;` and `{}` are special characters in PowerShell so are being interpreted by PowerShell (as a statement terminator and an empty scriptblock). If you add a backtick ` before each of these characters, everything should work as expected. This will prevent PowerShell from interpreting the characters and will pass them through to WSL.

```
find . -exec echo blub `;
find . -exec echo `{`} `;
```

The below also works and is a bit more natural.

```
find . -exec echo blub ";"
find . -exec echo "{}" ";"
```

The goal of both is to prevent PowerShell from interpreting these special characters and to pass them in as arguments to the command. The below doesn't work.

```
find . -exec "echo blub ;"
```

find expects the semicolon to be its own argument.

Let me know if that helps.

**Comment by aurora** [comment]
Thanks for your fast reply, the second option with the " also works with linux (and is also more easy to type on a german keyboard), so i am perfectly fine with the solution. 😄
