### ISSUE TITLE
Command execution broken in Powershell 7.3.0

### ISSUE THREAD

**Issue by jandhollander** [mikebattista/PowerShell-WSL-Interop#42]
**Describe the bug**
Executing a command that was imported using Import-WslCommand no longer executes with the following error in Powershell 7.3.0:
`/bin/bash: : command not found`

**To Reproduce**
- `Import-WslCommand ls`
- `ls`

**Expected behavior**
Execution of the command should work and error should not be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2222862/201093256-4c477629-3e61-4245-b3fe-39aff718531f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.4.0

**Additional context**
This works fine in Powershell 7.2.3 but confirmed broken after upgrade to 7.3.0

**Comment by gurnec** [comment]
This is the result of a (known) breaking change for the default value of the [`$PSNativeCommandArgumentPassing` preference variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#psnativecommandargumentpassing) from `Legacy` to `Windows`.

There are now two types of command argument escaping for native `.exe`s. `Legacy` is the old one, it attempted (but didn't fully succeed) to emulate `cmd.exe`-like behavior. `Standard` (the same as `Windows` as far as the `wsl.exe` executable is concerned) is very similar to standard PowerShell escaping. The only difference (I *think*) is that commas do not create Arrays when used with native commands (but do with PowerShell commands). All of the other `Legacy` escaping doesn't apply (double double-quotes `""`, `%` environment variable substitution, etc.).

This particular bug occurs when the `$commandLine` Array is built below. Several of the arguments are often the empty string, and these empty strings are actually passed to `wsl.exe` when using `Standard` escaping which confuses `wsl.exe`.

https://github.com/mikebattista/PowerShell-WSL-Interop/blob/8686e1f5f0d2e3411108cee127485311455f1eff/WslInterop.psm1#L95

Other changes to escaping and to temporarily setting `$PSNativeCommandArgumentPassing` will probably also be needed.

**Comment by mikebattista** [comment]
Thanks for letting me know. I'll take a look.

**Comment by mikebattista** [comment]
I filed https://github.com/mikebattista/PowerShell-WSL-Interop/pull/44 with a proposed fix. Could you import the module from the code in that branch and test locally?

I reproed the issue after updating to 7.3 and several Pester tests were failing. After making this change, all tests pass and the commands I import seem to be working ok. Argument completion doesn't seem to be impacted either but could use some more test coverage.

**Comment by jandhollander** [comment]
Thanks @mikebattista, this change seems to fix things for my case. I wasn't able to reproduce anymore.

**Comment by mikebattista** [comment]
Thanks for confirming.

**Comment by mikebattista** [comment]
I published https://github.com/mikebattista/PowerShell-WSL-Interop/releases/tag/v0.4.1 with this change.
