### ISSUE TITLE
`zsh:1: permission denied:`

### ISSUE THREAD

**Issue by felipecrs** [mikebattista/PowerShell-WSL-Interop#45]
**Describe the bug**
Hi. Thanks a lot for this project. It used to work very well, but recently I tried again and apparently all commands are failing with `zsh:1: permission denied:`.

**To Reproduce**
I can reproduce it locally, feel free to ask me any details.

**Expected behavior**
To work, I guess.

**Screenshots**
![image](https://user-images.githubusercontent.com/29582865/218338753-c6073a93-b107-4db9-8a29-25de830b97c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Version: 0.4.1

**Additional context**
Any help is really appreciated. Thanks!

**Comment by mikebattista** [comment]
I switched my shell to zsh and commands are still resolving for me.

Do you have any $WslDefaultParameterValues or $WslEnvironmentVariables set?

**Comment by felipecrs** [comment]
Mike, I tried to switch back to bash and the same issue remains:

```console
$ which ffmpeg
/bin/bash: line 1: : command not found
```

I don't have any $WslDefaultParameterValues or $WslEnvironmentVariables set.

Maybe this has something to do with newer PowerShell or WSL versions?

```console
❯ pwsh --version
PowerShell 7.3.2
❯ wsl --version
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1265
❯ wsl cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Are you by any chance running the same version as I?

**Comment by felipecrs** [comment]
I enabled some debug logs here, and I noticed something weird:


![image](https://user-images.githubusercontent.com/29582865/219419989-c8837dca-c7d6-4986-915a-28e24cc759d8.png)

$commandLine has some leading spaces in it, while I think there should not be any.

**Comment by felipecrs** [comment]
This is my $PROFILE:

```powershell
Import-WslCommand "cat", "cp", "echo", "find", "grep", "head", "ls", "mv", "rm", "sed", "touch", "tree", "which"
```

**Comment by mikebattista** [comment]
You might be hitting https://github.com/mikebattista/PowerShell-WSL-Interop/issues/42.

Can you update to the latest version of the WslInterop module?

**Comment by felipecrs** [comment]
Wow, that was it. I was using a very old version for whatever reason!

Sorry about it. It works now. Thank you!
