### ISSUE TITLE
Is there a way to export aliases from WSL2, so I can use them in PowerShell?

### ISSUE THREAD

**Issue by fmotion1** [mikebattista/PowerShell-WSL-Interop#47]
I have an alias `ll` for instance that is defined as `alias ll="ls -lhA --color=auto"` in `.bash_aliases`. How can I export this alias so that I can use it in PowerShell?

Thanks.

**Comment by fmotion1** [comment]
Never mind. Found a way. I added this to my profile and the alias works as expected:

```ps
Set-Alias -Name 'll' -Value Enhanced-LS
function Enhanced-LS {
    ls -lhA --color=auto
}
```

**Comment by mikebattista** [comment]
Awesome. Glad you found a solution.
