### ISSUE TITLE
Feature Request: Ability to define bash functions that can be used either in the shell or PowerShell profile.

### ISSUE THREAD

**Issue by fmotion1** [mikebattista/PowerShell-WSL-Interop#48]
**Is your feature request related to a problem? Please describe.**
I want to add the following `.bashrc` function for use (convert string file sizes to bytes):

```sh
toBytes() {
 echo $1 | echo $((`sed 's/.*/\L\0/;s/t/Xg/;s/g/Xm/;s/m/Xk/;s/k/X/;s/b//;s/X/ *1024/g'`))
}
```

**Describe the solution you'd like**
A way to define bash functions that can be used in my PowerShell profile or anywhere else.

**Describe alternatives you've considered**
Converting the bash function to a PowerShell function. This can be done, but I'd really like the option to just use the bash function.

**Additional context**
https://stackoverflow.com/questions/17615881/simplest-method-to-convert-file-size-with-suffix-to-bytes

**Comment by mikebattista** [comment]
PowerShell can't execute bash functions so you'd need a PowerShell wrapper. In your example, if you imported `sed` you should be able to implement a wrapper in your PowerShell profile that pipes the provided argument to `sed` using the parameters.
