### ISSUE TITLE
Awk not working correctly

### ISSUE THREAD

**Issue by speed65** [mikebattista/PowerShell-WSL-Interop#49]
**Describe the bug**
Awk is not working correctly when running in Powershell. It works in my WSL2 instance but not while using Interoped commands via the WslInterop module.

**To Reproduce**
So I created a test.txt file that I can use to get familiar with awk and then tried a simple command.
```
PS C:\Users\interopUser> touch test.txt
PS C:\Users\interopUser> echo "Name, Age, City" > test.txt
PS C:\Users\interopUser> echo "Alice, 25, New York" >> test.txt
PS C:\Users\interopUser> echo "Bob, 30, Los Angeles" >> test.txt
PS C:\Users\interopUser> echo "Charlie, 22, Chicago" >> test.txt
PS C:\Users\interopUser> echo "David, 35, Houston" >> test.txt
PS C:\Users\interopUser> echo "Eva, 28, Miami" >> test.txt
PS C:\Users\interopUser> cat .\test.txt
Name, Age, City
Alice, 25, New York
Bob, 30, Los Angeles
Charlie, 22, Chicago
David, 35, Houston
Eva, 28, Miami
PS C:\Users\interopUser> awk -F', ' '{print $2}' test.txt
Name, Age, City
Alice, 25, New York
Bob, 30, Los Angeles
Charlie, 22, Chicago
David, 35, Houston
Eva, 28, Miami
```

As you can see the awk command did not work correctly.

So then I tried to do the same in wsl2 see here:
```
interopUser@UAS2324401:~$ touch test.txt
interopUser@UAS2324401:~$ echo "Name, Age, City" > test.txt
echo "Alice, 25, New York" >> test.txt
echo "Bob, 30, Los Angeles" >> test.txt
echo "Charlie, 22, Chicago" >> test.txt
echo "David, 35, Houston" >> test.txt
echo "Eva, 28, Miami" >> test.txt
interopUser@UAS2324401:~$ cat test.txt
Name, Age, City
Alice, 25, New York
Bob, 30, Los Angeles
Charlie, 22, Chicago
David, 35, Houston
Eva, 28, Miami
interopUser@UAS2324401:~$ awk -F', ' '{print $2}' test.txt
Age
25
30
22
35
28
```

And as expected the awk command worked in WSL2

**Expected behavior**
The expected behavior is to have the awk command work in the same manner in Powershell as it does for WSL2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2
 - Build 22621.2283

**Additional context**
Here is what is being placed in my profile to help make this work:
`Import-WslCommand "grep", "tail", "touch", "man", "awk", "cut", "vim"`

**Comment by mikebattista** [comment]
I can get it working by embedding quotes inside the parameters like below.

```
> awk -F''', ''' '''{print $2}''' .\test.txt
awk: warning: escape sequence `\,' treated as plain `,'
awk: warning: escape sequence `\ ' treated as plain ` '
Age
25
30
22
35
28
```

You need the embedded quotes to make sure they're passed through as part of the parameter value inside WSL. Otherwise, PowerShell uses them to process the parameters but doesn't consider them part of the parameter itself.

**Comment by speed65** [comment]
Thanks for taking a look @mikebattista 

Please forgive me if is this sounds rude, but just know that I am not trying to be. 

Humble question:
I thought the point of your module was to allow correct functionality of the special characters such as the ' and not have to do corrective embedding or as you say "unnatural embedding"

Here is a quote from the fourth bullet on your README
_Arguments with special characters (e.g. regular expressions) are often misinterpreted without unnatural embedded quotes or escape sequences_

Thank you, 

This has been a great module that I have seen so far!

**Comment by mikebattista** [comment]
Are you able to run awk inside wsl without using the quotes? The way the module avoids embedded quotes in general is to escape the parameters when they are passed to WSL so they are interpreted correctly without the quotes.

If you need to pass quotes, then they'll need to be embedded. The first set of quotes are interpreted by PowerShell and not part of the arguments. And single vs. double quotes have different meanings so wrapping arguments that are passed to WSL would not always behave as expected.

**Comment by speed65** [comment]
So here is what happened when I tried the 3 different combos of quotes, and finally, the correct way.

```
speed65@UAS2324401:~$ awk -F', ' {print $2} test.txt
awk: cmd. line:1: {print
awk: cmd. line:1:       ^ unexpected newline or end of string
speed65@UAS2324401:~$ awk -F', {print $2} test.txt
>
> ^C
speed65@UAS2324401:~$ awk -F, {print $2} test.txt
awk: cmd. line:1: {print
awk: cmd. line:1:       ^ unexpected newline or end of string
speed65@UAS2324401:~$ awk -F', ' '{print $2}' test.txt
Age
25
30
22
35
28
```

Is there any way to tell Powershell or the module to grab the literal string following "awk" only when a command starts with the keyword "awk" so that the single quotes will not be interpreted by Powershell?

For Powershell maybe a change in the profile to do so.
For your module, well that's your dept. You would have to tell me. ;)

Just thinking out loud here.

Thank you,

**Comment by mikebattista** [comment]
I don't believe so and I certainly wouldn't want to hardcode a path just for "awk".
