### ISSUE TITLE
Install-Module WslInterop makes profile loading very slow

### ISSUE THREAD

**Issue by kitingChris** [mikebattista/PowerShell-WSL-Interop#50]
I tried using loading the WslInterop module in my profile. 
But then it makes loading the profile very slow...

![image](https://github.com/mikebattista/PowerShell-WSL-Interop/assets/757762/df9eb3f9-3a2c-48a1-8d4c-5931a034abcf)
![image](https://github.com/mikebattista/PowerShell-WSL-Interop/assets/757762/97906c57-ca1e-40cf-bf1e-ba3a6bf7ceea)

Implementing the function wrapper directly like explained in the [article ](https://devblogs.microsoft.com/commandline/integrate-linux-commands-into-windows-with-powershell-and-the-windows-subsystem-for-linux/) seems way more efficient. 

Or am I doing something wrong?

**Comment by mikebattista** [comment]
You shouldn't need to install the module in your profile. Just install it once then you just need `Import-WslCommand` in your profile to import the commands you want.
